CREATE TABLE IF NOT EXISTS "CategoriasMenu" (
  "CategoriaID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" varchar(255) NOT NULL,
  "Descripcion" text
);

CREATE TABLE IF NOT EXISTS "ItemsMenu" (
  "ItemID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" varchar(255) NOT NULL,
  "Imagen" varchar(255),
  "Descripcion" text,
  "Precio" decimal(10, 2) NOT NULL,
  "CategoriaID" integer NOT NULL REFERENCES "CategoriasMenu"("CategoriaID"),
  "Disponible" boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS "ItemsMenu_CategoriaID_idx"
  ON "ItemsMenu" ("CategoriaID");

INSERT INTO "CategoriasMenu" ("Nombre", "Descripcion")
SELECT 'Entradas', 'Para abrir el apetito con sabores colombianos'
WHERE NOT EXISTS (
  SELECT 1 FROM "CategoriasMenu" WHERE "Nombre" = 'Entradas'
);

INSERT INTO "CategoriasMenu" ("Nombre", "Descripcion")
SELECT 'Platos fuertes', 'Recetas tradicionales servidas con acompanamientos'
WHERE NOT EXISTS (
  SELECT 1 FROM "CategoriasMenu" WHERE "Nombre" = 'Platos fuertes'
);

INSERT INTO "CategoriasMenu" ("Nombre", "Descripcion")
SELECT 'Bebidas y postres', 'Jugos naturales, dulces y sobremesa'
WHERE NOT EXISTS (
  SELECT 1 FROM "CategoriasMenu" WHERE "Nombre" = 'Bebidas y postres'
);

INSERT INTO "ItemsMenu" (
  "Nombre",
  "Imagen",
  "Descripcion",
  "Precio",
  "CategoriaID",
  "Disponible"
)
SELECT
  item."Nombre",
  item."Imagen",
  item."Descripcion",
  item."Precio",
  category."CategoriaID",
  true
FROM (
  VALUES
    ('Empanadas vallunas', '/images/empanadas.jpg', 'Masa de maiz, carne desmechada, papa criolla y aji de la casa.', 14000.00, 'Entradas'),
    ('Patacones con hogao', '/images/patacones.jpg', 'Platano verde crocante con tomate, cebolla larga y cilantro.', 13000.00, 'Entradas'),
    ('Bandeja paisa', '/images/bandeja-paisa.jpg', 'Frijoles, arroz, chicharron, carne molida, huevo, platano y aguacate.', 34000.00, 'Platos fuertes'),
    ('Sancocho de gallina', '/images/sancocho.jpg', 'Caldo casero con gallina, yuca, platano, papa y cilantro fresco.', 32000.00, 'Platos fuertes'),
    ('Limonada de panela', '/images/limonada-panela.jpg', 'Panela, limon fresco y hielo.', 8000.00, 'Bebidas y postres'),
    ('Tres leches', '/images/tres-leches.jpg', 'Bizcocho suave, crema de leche y toque de canela.', 11000.00, 'Bebidas y postres')
) AS item("Nombre", "Imagen", "Descripcion", "Precio", "CategoriaNombre")
JOIN "CategoriasMenu" category ON category."Nombre" = item."CategoriaNombre"
WHERE NOT EXISTS (
  SELECT 1 FROM "ItemsMenu" existing WHERE existing."Nombre" = item."Nombre"
);
