export const ORDER_COPY = {
  es: {
    title: "Pedido online",
    subtitle: "Elige los platos, revisa tu cesta y deja tus datos.",
    preview:
      "Vista previa: este pedido solo se guarda en este navegador y aparece en el panel de empleados de esta misma instalación. No se envía al restaurante ni se realiza ningún cobro.",
    search: "Buscar platos",
    searchPlaceholder: "Buscar en la carta",
    all: "Todos",
    add: "Añadir",
    unavailablePrice: "Precio no disponible",
    emptyMenu: "No hay platos disponibles para esta búsqueda.",
    cart: "Tu pedido",
    emptyCart: "Añade platos de la carta para empezar.",
    remove: "Quitar",
    subtotal: "Total",
    details: "Datos para el pedido",
    pickup: "Recoger en local",
    delivery: "A domicilio",
    name: "Nombre",
    phone: "Teléfono",
    address: "Dirección de entrega",
    notes: "Notas para cocina",
    notesPlaceholder: "Alergias, cambios o instrucciones",
    place: "Registrar pedido de prueba",
    success: "Pedido registrado",
    successText:
      "El pedido ya aparece como nuevo en el panel de empleados de este navegador.",
    orderNumber: "Número de pedido",
    another: "Hacer otro pedido",
    viewEmployees: "Ver panel de empleados",
    saveError:
      "No se pudo guardar el pedido en este navegador. Comprueba el espacio disponible e inténtalo de nuevo.",
    quantity: "Cantidad",
    steps: ["Platos", "Datos", "Pago"],
    nextDetails: "Continuar con datos",
    nextPayment: "Continuar al pago",
    backToDishes: "Volver a los platos",
    backToDetails: "Volver a tus datos",
    payment: "Pago",
    paymentIntro: "Revisa los datos y el importe antes de registrar el pedido.",
    paymentPreview:
      "Vista previa de pago: todavía no hay pasarela conectada. No introduzcas datos bancarios; no se realizará ningún cargo.",
    paymentMethod: "Método de pago",
    card: "Tarjeta",
    bank: "PSE",
    cardNumber: "Número de tarjeta",
    cardExpiry: "Caducidad",
    cardCvc: "CVC",
    selectBank: "Selecciona tu banco",
    paymentPending:
      "Los campos de pago se habilitarán cuando se integre la pasarela.",
    requiredDetails: "Completa los datos de contacto para continuar.",
  },
  en: {
    title: "Order online",
    subtitle: "Choose your dishes, review your basket and enter your details.",
    preview:
      "Preview only: this order is saved in this browser and appears in the employee dashboard of this installation. It is not sent to the restaurant and no payment is taken.",
    search: "Search dishes",
    searchPlaceholder: "Search the menu",
    all: "All",
    add: "Add",
    unavailablePrice: "Price unavailable",
    emptyMenu: "No dishes match your search.",
    cart: "Your order",
    emptyCart: "Add dishes from the menu to get started.",
    remove: "Remove",
    subtotal: "Total",
    details: "Order details",
    pickup: "Pick up",
    delivery: "Delivery",
    name: "Name",
    phone: "Phone",
    address: "Delivery address",
    notes: "Kitchen notes",
    notesPlaceholder: "Allergies, changes or instructions",
    place: "Register preview order",
    success: "Order registered",
    successText:
      "Your order now appears as a new order in this browser's employee dashboard.",
    orderNumber: "Order number",
    another: "Place another order",
    viewEmployees: "Open employee dashboard",
    saveError:
      "The order could not be saved in this browser. Check available storage and try again.",
    quantity: "Quantity",
    steps: ["Dishes", "Details", "Payment"],
    nextDetails: "Continue to details",
    nextPayment: "Continue to payment",
    backToDishes: "Back to dishes",
    backToDetails: "Back to your details",
    payment: "Payment",
    paymentIntro: "Review your details and total before registering the order.",
    paymentPreview:
      "Payment preview: no gateway is connected yet. Do not enter bank details; no charge will be made.",
    paymentMethod: "Payment method",
    card: "Card",
    bank: "PSE",
    cardNumber: "Card number",
    cardExpiry: "Expiry date",
    cardCvc: "CVC",
    selectBank: "Select your bank",
    paymentPending:
      "Payment fields will be enabled when the gateway is integrated.",
    requiredDetails: "Complete your contact details to continue.",
  },
};

export type OrderCopy = (typeof ORDER_COPY)["es"];
